controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 30.0
    allowed_goal_duration_margin: 15.0 
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
